# Generated by Django 4.1 on 2022-10-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genius', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
